baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stephenajulu.com" # the base hostname & protocol for your site, e.g. http://example.com

author: Stephen Ajulu
title: Stephen Ajulu
description: Stephen Ajulu is a Student, Frond End Web Developer, Graphics/UI/UX Designer, Ethical Hacker and Consultant. Here he showcases his skills, knowledge, education and portfolio
keywords: stephen, ajulu, personal, stephen odero ajulu otieno, stephenajulu, jekyll, stephen ajulu, portfolio, odero, stephen odero ajulu, tech, cybersecurity, ajulu's thought's, blog, website, github pages, stephenajulu.github.io, web developer, graphic designer, I.T expert, alusa, stehen ajulu alusa



# Social Buttons
social:
  - title: "facebook"
    url: "https://facebook.com/stephenajulu"
  - title: "twitter"
    url: "https://twitter.com/stephenajulu"
  - title: "instagram"
    url: "https://www.instagram.com/stephenajulu"
  - title: "github"
    url: "https://github.com/stephenajulu"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/stephenajulu/"
  - title: "wordpress"
    url: "https://ajulusthoughts.wordpress.com"
  - title: "rss"
    url: "/feed.xml"
  - title: "bitcoin"
    url: "https://www.blockchain.com/btc/address/1DJxuX44dLtTFbBXdaBZUpwhLEh2DLDP5w"
  - title: "user-crown"
    url: "https://wybemf.com/stephenajulu"
  - title: "website"
    url: "https://stephenajulu.com"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  
# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
