#-------------------------------
# General Site Settings

title: Stephen Odero Ajulu
logo: logo.png
email: ajulu@stephenajulu.com
phone: +254 726 024 210
address: Nairobi, Kenya

menu:
- {name: About, link: '/about'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}
- {name: Blog, link: '/blog'}

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: UA-132349593-3


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: thoughtsofajulu # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Stephen Ajulu<br>

social:
- {icon: "ti-facebook", link: "https://www.facebook.com/stephenajulu"}
- {icon: "ti-instagram", link: "https://www.instagram.com/stephenajulu"}
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/stephenajulu/"}
- {icon: "ti-twitter", link: "https://twitter.com/stephenajulu"}
- {icon: "ti-github", link: "https://github.com/stephenajulu/"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UC043ZXL-t3yqtgcIxJmkHuA?view_as=subscriber"}
- {icon: "ti-email", link: "mailto:ajulu@stephenajulu.com"}
- {icon: "ti-wordpress", link: "https://ajulusthoughts.wordpress.com"}
- {icon: "ti-dribble", link: "https://dribbble.com/stephenajulu"}
- {icon: "ti-pinterest", link: "https://pinterest.com/stephenajulu/"}

#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I am a Front End Web Developer, Graphic Designer, Ethical Hacker, Content Creator and Researcher. I am currently pursuing a bachelor of science in Information Technology....

blurb-btn-link: '/about'
blurb-btn-name: learn more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "I conduct a research based on the client's specifications then plan the work"
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "After Research and Planning, i then develop/create/design the product/service"
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "After Designing and Developing i deliver the desired product/service to the client, with instructions how to operate the product/service"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Web Development & Search Engine Optimization, color: '#993299', value: '82%'}
- {name: Graphics/UI/UX Design, color: '#BA3641', value: '55%'} # 9473e6
- {name: Ethical Hacking & Cybersecurity, color: '#329932', value: '73%'}
- {name: Information Technology, color: '#193E71', value: '85%'}
- {name: Social Media Managment and Marketing, color: '#57737', value: '89%'}

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Monitoring & Evaluation Secretariate, icon: 'icon-1.png', date: 'Nov 2015 - Dec 2015', organization: 'Ministry of Devolution and Planning, Kenya'}
- {name: M&E Secretariate/Tech Support, icon: 'icon-2.png', date: 'Nov 2016 - Dec 2016', organization: 'Ministry if Devolution and Planning, Kenya'}
- {name: I.T & Cybersecurity Consultant, icon: 'icon-3.png', date: 'Aug 2014 - Present', organization: 'Gogan Investments, Ajulu Technologies and Alusa SS Investments'}

#-------------------------------
# Education Section

education-title: Education
education:
- {name: Bachelor of Science in Information Technology, date: 'Ongoing', organization: 'Mount Kenya University'}
- {name: Introduction to Cybersecurity, date: '2019', organization: 'IBM Digital & CISCO Netcad'}
- {name: Introduction to Cloud Computing, date: '2019', organization: 'IBM Digital'}
- {name: Certified Ethical Hacker, date: '2018', organization: 'Institute of Software Technologies'}
- {name: Diploma in Information Technology, date: '2017', organization: 'St. Pauls University'}
- {name: Fundamental System Troubleshooting, date: '2016', organization: 'Cybrary.it'}
- {name: Certificate in Photoshop and Corel Draw, date: '2016', organization: 'Epren College of Professional Studies'}
- {name: Certificate in Business Information Technology, date: '2016', organization: 'St. Pauls University'}
- {name: French Level 1, data: '2015', organization: 'Epren College of Proffesional Studies'}
- {name: Kenya Certificate of Secondary Education, date: '2014', organization: 'Highway Secondary School'}

#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Graphics/UI/UX Design,
    icon: ti-palette,
    description: 'I create logos, posters, flyers, business cards, interfaces among others.',
    active: 
  }
- {
    name: Web Development,
    icon: ti-world,
    description: 'I design and develop websites for individuals, small businesses(SMEs), companies and the government.',
    active: true # Add tr
  }
- {
    name: Information Technology and Cybersecurity Consultation,
    icon: ti-desktop,
    description: 'I provide technical advice and give market proven strategies.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/website (1).jpg"
    url: "https://owlsectechnologies.wordpress.com"
    
  - image : "assets/images/portfolio/website (2).jpg"
    url: "https://ajulusthoughts.wordpress.com"
    
  - image : "assets/images/portfolio/website (7).jpg"
    url: "https://stephenajulu.com"
    
  - image : "assets/images/portfolio/website (4).jpg"
    url: "https://quevant.weebly.com"
    
  - image : "assets/images/portfolio/website (5).jpg"
    url: "https://05739.wixsite.com/stephenajulu"

  - image : "assets/images/portfolio/website (6).jpg"
    url: "https://05739.wixsite.com/quevant"
    
# Portfolio Page
portfolio-label:
- {
    title : "GRAPHICS DESIGN",
    type : "design"
  }
- {
    title : "WEB DEVELOPMENT & DESIGN",
    type : "website"
  }
- {
    title : "USER INTERFACE & EXPERIENCE",
    type : "uiux"
  }

portfolio-items:
  - image : "assets/images/portfolio/Screenshot_2019-08-23 Ajulus Thoughts (2).jpg"
    url: "https://ajulusthoughts.wordpress.com"
    portfolio-type:
      - type: "website"

  - image : "assets/images/portfolio/Screenshot_2019-08-23 Stephen Ajulu.jpg"
    url: "https://stephenajulu.com"
    portfolio-type:
      - type: "website"

  - image : "assets/images/portfolio/Screenshot_2019-08-23 Stephen Ajulu.png"
    url: "https://stephenajulu.com/v0"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/Screenshot_2019-09-26 Ajulu's Merch.jpg"
    url: "https://ajulusmerch.ecwid.com"
    portfolio-type:
      - type: "website"
     
  - image : "assets/images/portfolio/Screenshot_2019-09-26 Ajulu's Thoughts.jpg"
    url: "https://ajulusthoughts.github.io"
    portfolio-type:
      - type: "website"
     
  - image : "assets/images/portfolio/Screenshot_2019-09-26 Ajulu's Thoughtsheroku.jpg"
    url: "https://ajulusblog.herokuapp.com"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/Screenshot_2019-09-26 OwlSec Technologies.jpg"
    url: "https://owlsectechnologies.wordpress.com"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/Screenshot_2019-09-26 Stephen Ajulu.jpg"
    url: "https://stephenajulu.com"
    portfolio-type:
      - type: "website"
   
  - image : "assets/images/portfolio/Screenshot_2019-10-07 Ajulu's Thoughts.jpg"
    url: "https://ajulusblog.herokuapp.com"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/Screenshot_2019-10-07 Home - OwlSec Technologies.png"
    url: "https://owlsectechnologies.netlify.com"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/Screenshot_2019-10-07 { Stephen Odero Ajulu }.png"
    url: "https://stephenajulu.com/v2"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/Tech6.png"
    url: "https://stephenajulu.com/v2"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/A.jpg"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/AJULU TECH PERFECT BLACK 3.jpg"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/BROTEMU 1.8.jpg"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/falcks 4.JPG"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/IMG_20180410_224713.JPG"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/Primetech logo 10.1.jpg"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/Untnitled.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/unhtitled.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/Untitled-2.jpg"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/jpng.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/ajulu-channel-art-matte.jpg"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/Quevant estore1 transperent.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/My Post.png.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image : "assets/images/portfolio/My Post1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/My Post10.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/My Post11.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/My Post5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/My Post8.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/My Post9.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/My Post4.png"
    url: "#"
    portfolio-type:
      - type: "design"
      

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: ajulu@stephenajulu.com
