#-------------------------------
# General Site Settings

title: Stephen Odero Ajulu
logo: logo.png
email: ajulu@stephenajulu.com
phone: +254 726 024 210
address: Nairobi, Kenya

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}
- {name: Gear, link: '/gear'}
- {name: Shop, link: '/shop'}

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: UA-132349593-3


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: thoughtsofajulu # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Stephen Ajulu<br>

social:
- {icon: "ti-facebook", link: "https://www.facebook.com/stephenajulu"}
- {icon: "ti-instagram", link: "https://www.instagram.com/stephenajulu"}
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/stephenajulu/"}
- {icon: "ti-twitter", link: "https://twitter.com/stephenajulu"}
- {icon: "ti-github", link: "https://github.com/stephenajulu/"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UC043ZXL-t3yqtgcIxJmkHuA?view_as=subscriber"}
- {icon: "ti-reddit", link: "https://www.reddit.com/user/4julu"}
- {icon: "ti-wordpress", link: "https://ajulusthoughts.wordpress.com"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  How are you? My name is Stephen Ajulu. I am a Front End Web Developer, Graphic Designer, Ethical Hacker, Blogger, Researcher and An Avid Job Seeker. I am currently pursuing a bachelor of science in Information Technology....

blurb-btn-link: '/about'
blurb-btn-name: learn more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "I conduct a research based on the client's specifications then plan the work"
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "After Research and Planning, i then develop/create/design the product/service"
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "After Designing and Developing i deliver the desired product/service to the client, with instructions how to operate the product/service"

# My Team Section
# team:
#  - title : "Stephen Ajulu"
#    image : "assets/images/team/member-1.png"
#    designation : "I.T and Cybersecurity Consultant"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Web Development, color: '#fdb157', value: '77%'}
- {name: Graphics/UI/UX Design, color: '#9473e6', value: '65%'}
- {name: Ethical Hacking, color: '#bdecf6', value: '60%'}
- {name: Information Technology, color: '#ffbcaa', value: '80%'}
- {name: Researching, color: '#1aff1a', value: '95%'}
- {name: Cybersecurity, color: '#cc33ff', value: '76%'}
- {name: Search Engine Optimization, color: '#ffff00', value: '76%'}
- {name: Social Media Marketing, color: '#ff8533', value: '60%'}

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Monitoring & Evaluation Secretariate, icon: 'icon-1.png', date: 'Nov 2015 - Doc 2014', organization: 'Ministry of Devolution and Planning, Kenya'}
- {name: M&E Secretariate/Tech Support, icon: 'icon-2.png', date: 'Nov 2015 - Dec 2015', organization: 'Ministry if Devolution and Planning, Kenya'}
- {name: I.T & Cybersecurity Consultant, icon: 'icon-3.png', date: 'Nov 2016 - Present', organization: 'Gogan Investments, Ajulu Technologies and Alusa SS Investments'}

#-------------------------------
# Education Section

education-title: Education
education:
- {name: Bachelor of Science in Information Technology, date: 'Ongoing', organization: 'Mount Kenya University'}
- {name: Introduction to Cybersecurity, date: '2019', organization: 'IBM Digital & CISCO Netcad'}
- {name: Introduction to Cloud Computing, date: '2019', organization: 'IBM Digital'}
- {name: Certified Ethical Hacker, date: '2018', organization: 'Institute of Software Technologies'}
- {name: Diploma in Information Technology, date: '2017', organization: 'St. Pauls University'}
- {name: Fundamental System Troubleshooting, date: '2016', organization: 'Cybrary.it'}
- {name: Certificate in Photoshop and Corel Draw, date: '2016', organization: 'Epren College of Professional Studies'}
- {name: Certificate in Business Information Technology, date: '2016', organization: 'St. Pauls University'}
- {name: French Level 1, data: '2015', organization: 'Epren College of Proffesional Studies'}
- {name: Kenya Certificate of Secondary Education, date: '2014', organization: 'Highway Secondary School'}

#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Graphics/UI/UX Design,
    icon: ti-palette,
    description: 'I create logos, posters, flyers, business cards, interfaces among others.',
    active: # Add true to select section
  }
- {
    name: Web Development,
    icon: ti-world,
    description: 'I design and develop websites for individuals, small businesses(SMEs), companies and the government.',
    active: true # Add true to select section
  }
- {
    name: Information Technology and Cybersecurity Consultation,
    icon: ti-desktop,
    description: 'I provide technical advice and give market proven strategies.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/website (1).jpg"
    url: "https://owlsectechnologies.wordpress.com"
    
  - image : "assets/images/portfolio/website (2).jpg"
    url: "https://ajulusthoughts.wordpress.com"
    
  - image : "assets/images/portfolio/website (7).jpg"
    url: "https://stephenajulu.com"
    
  - image : "assets/images/portfolio/website (4).jpg"
    url: "https://quevant.weebly.com"
    
  - image : "assets/images/portfolio/website (5).jpg"
    url: "https://05739.wixsite.com/stephenajulu"

  - image : "assets/images/portfolio/website (6).jpg"
    url: "https://05739.wixsite.com/quevant"
    
# Portfolio Page
portfolio-label:
- {
    title : "GRAPHICS/UI/UX DESIGN",
    type : "design"
  }
- {
    title : "WEB DEVELOPMENT",
    type : "website"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image : "assets/images/portfolio/website (1).jpg"
    url: "#"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/website (2).jpg"
    url: "#"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/website (3).jpg"
    url: "#"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/website (4).jpg"
    url: "#"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/website (5).png"
    url: "#"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/website (6).png"
    url: "#"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/website (7).png"
    url: "#"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/website (8).png"
    url: "#"
    portfolio-type:
      - type: "website"
      
  - image : "assets/images/portfolio/website (9).png"
    url: "#"
    portfolio-type:
      - type: "website"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Morris Juno Ojwang"
    image: "assets/images/testimonial/client-1.png"
    designation : "CEO/Founder of Primetech Solutions"
    content : "I approached Stephen because i wanted a logo, he delivered beyond my expectations. Even my customers loved the logo design."

#-------------------------------
# Client Slider Section

#client-slider-items:
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#   url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-1.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-2.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-3.png"
#    url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-4.png"
#   url: "#"
    
#  - logo: "assets/images/clients-logo/client-logo-5.png"
#    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: ajulu@stephenajulu.com
